import { hashFile, implementationPins } from './capability_pins.js';
import { digest, requireThat } from './protocol.js';
import { FORGE_ACTIONS, RECIPE_QUERY_POLICY, RECIPE_PAGE_POLICY, RECIPE_NAVIGATION_POLICY, QUEST_POLICY, QUEST_TEXT_POLICY, QUEST_COMPONENTS_POLICY, QUEST_MENU_POLICY, QUEST_OPEN_POLICY, QUEST_NAVIGATION_POLICY, QUEST_TASK_POLICY, QUEST_REWARD_POLICY, QUEST_MENU_ACTION_POLICY } from './native_game.js';
import { guardImplementationDigest } from './forge_guard.js';

/** Separate D06 identity; never inherit Mineflayer/pathfinder compatibility claims. */
export function forgeCapabilities(nativeFingerprint: string) {
  requireThat(/^[a-f0-9]{64}$/.test(nativeFingerprint), 'CAPABILITY_MISSING');
  const sources = implementationPins();
  const schemas = Object.fromEntries(['ActionBatch','ActionAck','Observation','RpcRequest']
    .map(name => [name, hashFile(new URL(`../../../../schemas/v1/public/${name}.json`, import.meta.url))]));
  return {
    schema:'strata/Capabilities/1', contract_minor:35, profile:'forge1192-structured-development/1',
    backend:'forge_client', track:'structured-actions/v1', minecraft:'1.19.2', forge:'43.4.23',
    target_pack:'enigmatica9expert-1.27.0', node:'24.19.0', native_fingerprint:nativeFingerprint,
    implementation_digest:digest(sources), schema_digest:digest(schemas),
    dependency_lock_digest:hashFile(new URL('../../package-lock.json', import.meta.url)),
    actions:FORGE_ACTIONS, keybindings:false, screenshots:false, recipes:true, quests:true, wait_events:true,
    quest_menu_action:{policy:QUEST_MENU_ACTION_POLICY,source:'ftb_quests',operations:['back','scroll'],
      scroll:'one-native-wheel-step-up-or-down',hover:'temporary-logical-target-restored-no-os-pointer-move',
      context:'exact-item-or-opening-bound-choice-menu-with-own-parent-book',
      back:{item:'visible-back-button',choice:'native-backspace-onBack',pointer:'native-parent-restoration'},
      choice_scroll:'attached-vertical-scrollbar-value-and-panel-confirmed',claims:false,server_effects_verified:false,conformance:'unverified'},
    quest_reward:{policy:QUEST_REWARD_POLICY,source:'ftb_quests',operations:['open'],scope:'visible-eligible-choice-reward-button',
      confirmation:'same-opened-menu-and-parent-book',claims:false,conformance:'unverified'},
    quest_task:{policy:QUEST_TASK_POLICY,source:'ftb_quests',operations:['open'],
      selection:'visible-task-page-and-current-book',target:'exact-visible-enabled-item-task-button',
      result:'item-alternatives-or-origin-bound-task-recipes',single_item_nonconsuming_jei:true,
      jei_artifacts:'exact-quests-library-teams-xmod-jei-sha256/1',jei_current_page:'slot_header_control_draw_operands',submit:false,
      server_effects_verified:false,conformance:'unverified'},
    quest_navigation:{policy:QUEST_NAVIGATION_POLICY,source:'ftb_quests',operations:['chapter','quest','back','close'],
      selection:'visible-catalog-page-generation-revision',context:'current-exact-book-or-opening-bound-task-recipes',
      mutations:'ordinary-native-link-back-and-close',task_recipes:'origin-state-and-close-to-book-only',
      recipe_history:false,recipe_current_page:'slot_header_control_draw_operands',tasks:false,scroll:false,server_effects_verified:false,conformance:'unverified'},
    recipe_page:{policy:RECIPE_PAGE_POLICY,source:'jei',coverage:'slot_header_control_draw_operands',complete:false,
      context:'origin-bound-task-recipes',empty_layouts:'observed-complete-native-loop',layouts:32,slots_per_layout:128,bytes:32768,native_frame_age_ms:250,projection_ms:100,
      copied:true,clipping:'explicit-omission',custom_components:'unsupported',labels:2,label_codepoints:1024,controls:4,control_mutations:'separate-recipe_navigate-action',
      overlay_visibility_verified:false,mutations:false,conformance:'unverified'},
    recipe_navigation:{policy:RECIPE_NAVIGATION_POLICY,source:'jei',controls:['category_next','category_previous','page_next','page_previous'],
      context:'origin-bound-task-recipes',selection:'source-screen-page-revision-and-drawn-enabled-control',
      dispatch:'page-controls-SIMULATE-then-EXECUTE-or-public-history-callback',confirmation:'ordinary-dispatch-and-fresh-complete-frame',
      wait_ticks:200,cancellation:'ordinary-router-handleGuiChange-without-click',
      history:{control:'history_back',dispatch:'ordinary-public-RecipesGui.back-callback',empty:'no-op-keeps-screen',
        private_history:false,physical_hotkey:false,minimum_primitives:3},page_minimum_primitives:4,
      completion:'emitted-input-only',conformance:'unverified'},
    quest_open:{policy:QUEST_OPEN_POLICY,source:'ftb_quests',operations:['open'],
      context:'survival-no-screen-idle-input-own-team-non-editing',catalog:'root-source-generation-and-revision',
      dispatch:'ordinary-ftb-openGui-once',confirmation:'exact-local-screen-identity',server_effects_verified:false,conformance:'unverified'},
    quest_menu:{policy:QUEST_MENU_POLICY,source:'ftb_quests',scope:'current-visible-item-or-opening-bound-choice-menu',
      inspected_items:512,page:32,bytes:32768,entry_bytes:16384,controls_bytes:8192,tooltip_lines:64,projection_ms:100,
      modifiers:'released',advanced_tooltips:false,mutations:false,choices:true,choice_claims:false,conformance:'unverified'},
    quest_components:{policy:QUEST_COMPONENTS_POLICY,source:'ftb_quests',scope:'visible-own-quest-task-reward-normal-tooltips',
      entries:512,page:32,bytes:32768,entry_bytes:16384,tooltip_lines:64,projection_ms:100,modifiers:'released',
      advanced_tooltips:false,choice_options:false,mutations:false,conformance:'unverified'},
    quest_text:{policy:QUEST_TEXT_POLICY,source:'ftb_quests',scope:'one-visible-own-quest-plain-text',lines:512,page:32,
      bytes:32768,projection_ms:100,rich_content:'explicit-unsupported',tasks:false,rewards:false,mutations:false,conformance:'unverified'},
    quest_catalog:{policy:QUEST_POLICY,source:'ftb_quests',version:'1902.5.10-build.497',
      scope:'visible-chapter-quest-catalog-own-team',artifact_pins:'exact-quests-library-teams-sha256/1',
      matches:4096,page:32,bytes:32768,title_codepoints:1024,projection_ms:100,
      details:false,tasks:false,rewards:false,mutations:false,conformance:'unverified'},
    recipe_policy:'player-book-exact-shaped-shapeless-pages32/1',
    machine_observation:{policy:'thermal-current-gui-energy-fluid-base-slots/1',
      menus:['thermal:machine_furnace','thermal:machine_crucible'],
      versions:{thermal_expansion:'10.3.1.25',thermal:'10.3.0.9',cofh_core:'10.3.1.48'},
      artifact_pins:'exact-three-loaded-jar-sha256/1',
      source:'current-client-gui',augment_slots:false,slots:'base-and-player-active-only',
      slot_mutations:'visible-pickup-and-machine-to-player-quick-move',controls:false,progress:false,conformance:'unverified'},
    recipe_query:{policy:RECIPE_QUERY_POLICY,source:'jei',version:'11.8.1.1034',
      categories:['minecraft:crafting','thermal:furnace','thermal:crucible'],focus:['item','fluid'],
      machine_source:'exact-thermal-jei-layout-simple-untagged-ingredients',machine_execution:false,
      roles:['input','output'],matches:512,page:32,bytes:32768,projection_ms:100,conformance:'unverified'},
    public_signals:{policy:'action-status-only/1',ring:128,delivery_limit:32,max_wait_ms:3000},
    observation:{policy:'opaque-voxel-fixed305-radius16/2',radius:16,entries:128,snapshot_bytes:65536,
      deliveries_per_second:2,components:[],pagination:true,cursor_ttl_ms:30000,
      clock_mapping:'conservative-request-bound/1',identity:'native-client-thread-body-generation/1'},
    motor:{policy:'durable-intent-client-thread-nineteen-actions/2',completion:'emitted-input-only',
      block_target:'observed-outline-centers64-local16/1',
      close_window:'explicit-close-own-inventory-feedback-conservation/1',
      crafting:'known-recipe-book-fill-single-output-remainders/1',
      manual_crafting:'visible-recipe-manual-grid-feedback-search4096/1',
      manual_crafting_limits:{source:'jei',selection:'query-generation-initial-revision-and-current-definition/1',
        ingredient_search:4096,grid:9,inventory_slots:36,clicks_per_ingredient:3},
      tick_phase:'start',held_use_ms:2000,chat_utf16_units:256,entity_hand:'main',
      primitives:'one-per-look-gesture-held-tick-movement-tick-menu-wait-click-refresh-and-safety-release/2',
      navigation:'delivered-shapes-level-bfs512-radius16/1',collision:'delivered-static-vanilla-shapes-age30s/1',
      movement:'level-forward-coast-neutral8-charged-ticks/1',
      movement_limits:{level_only:true,radius:16,expansions:512,cell_reads:4096,waypoints:64,plan_ms:20,map_age_ms:30000},
      movement_settings:{auto_jump:false,toggle_sprint:false,toggle_crouch:false},
      inventory_feedback:'fixed-open-menu-full-refresh/1',placement:'observed-air-face-blockitem/1'},
    machine_inventory:{policy:'thermal-visible-slot-owned-transfer-feedback/2',
      input_policy:'thermal-display-independent-slot-cursor-fence/1',
      prediction:'ordinary-native-click-conserved-visible-resources',confirmation:'server-owned-slots-and-cursor-exact',
      pre_click_echo:'one-charged-refresh-no-click-replay',machine_processing:'not-attributed-to-click',hidden_slots:'not-read',player_to_machine_quick_move:false},
    release:{policy:'confirmed-native-release/1',timeout_ms:250,fence_on_stop_all:true},
    process_guard:{policy:'forge-process-listener-client-thread/1',platform:'win32',python:'3.12.14',
      implementation_digest:guardImplementationDigest(),parent_lease_ms:1500,native_stale_ms:1500,
      native_health_period_ms:1000,termination_wait_ms:500,whole_client_lifetime:true},
    limits:{movement_ms:30000,action_ms:10000,observation_age_ms:2000},
    conformance:'unverified', campaign_admission:false, operator_development_only:true,
  };
}
