modLoader="javafml"
loaderVersion="[43,44)"
license="MIT"

[[mods]]
modId="strata_client"
version="0.1.0"
displayName="Strata client development extension"
description='''Operator settings and filtered game observation bridges. No qualified control backend yet.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.strata_client]]
modId="forge"
mandatory=true
versionRange="[43.4.23]"
ordering="NONE"
side="CLIENT"

[[dependencies.strata_client]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="CLIENT"
